-- Write your query below
SELECT SP.NAME
FROM SALES_PERSON SP
LEFT JOIN ORDERS O
ON SP.SALES_ID = O.SALES_ID
LEFT JOIN COMPANY C
ON O.COM_ID = C.COM_ID
GROUP BY SP.SALES_ID,SP.NAME
HAVING COUNT(*) FILTER (WHERE C.NAME = 'CRIMSON') = 0