-- Write your query below
SELECT U.NAME,COALESCE(SUM(DISTANCE)::NUMERIC,0::NUMERIC) AS TRAVELLED_DISTANCE
FROM USERS U
LEFT JOIN RIDES R
ON U.ID = R.USER_ID
GROUP BY U.NAME,U.ID
ORDER BY TRAVELLED_DISTANCE DESC, U.NAME