-- Write your query below
WITH CTE AS (
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,STRING_AGG(DISTINCT PRODUCT_NAME, ',' ORDER BY PRODUCT_NAME) AS TOTAL
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME
)
SELECT CUSTOMER_ID, CUSTOMER_NAME
FROM CTE
WHERE TOTAL LIKE '%A%B%' AND TOTAL NOT LIKE '%C%'
ORDER BY CUSTOMER_NAME