-- Write your query below
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME
HAVING 
COUNT(*) FILTER (WHERE O.PRODUCT_NAME = 'A') > 0 AND 
COUNT(*) FILTER (WHERE O.PRODUCT_NAME = 'B') > 0 AND 
COUNT(*) FILTER (WHERE O.PRODUCT_NAME = 'C') = 0
ORDER BY C.CUSTOMER_NAME