-- Write your query below
SELECT DISTINCT C.CUSTOMER_ID, C.CUSTOMER_NAME
FROM CUSTOMERS C
JOIN ORDERS O1
ON C.CUSTOMER_ID = O1.CUSTOMER_ID AND O1.PRODUCT_NAME = 'A'
JOIN ORDERS O2
ON C.CUSTOMER_ID = O2.CUSTOMER_ID AND O1.PRODUCT_NAME = 'A' AND O2.PRODUCT_NAME = 'B'
LEFT JOIN ORDERS O3
ON C.CUSTOMER_ID = O3.CUSTOMER_ID AND O1.PRODUCT_NAME = 'A' AND O2.PRODUCT_NAME = 'B' AND O3.PRODUCT_NAME = 'C'
WHERE O3.PRODUCT_NAME IS NULL
ORDER BY C.CUSTOMER_NAME