-- Write your query below
SELECT E1.STUDENT_ID, E1.EXAM_ID, E1.SCORE
FROM EXAM_RESULTS E1
WHERE NOT EXISTS
(
SELECT 1 FROM EXAM_RESULTS E2
WHERE E1.STUDENT_ID = E2.STUDENT_ID AND ((E2.SCORE > E1.SCORE) 
OR (E1.SCORE = E2.SCORE AND E1.EXAM_ID > E2.EXAM_ID))
)
ORDER BY E1.STUDENT_ID