-- Write your query below
WITH PROCESSED AS (
SELECT *,ROW_NUMBER() OVER(PARTITION BY STUDENT_ID ORDER BY SCORE DESC,EXAM_ID) AS RN
FROM EXAM_RESULTS
)
SELECT STUDENT_ID,EXAM_ID,SCORE
FROM PROCESSED
WHERE RN = 1