-- Write your query below
SELECT LEFT_OPERAND, OPERATOR, RIGHT_OPERAND, 
CASE 
    WHEN OPERATOR = '=' THEN V1.VALUE = V2.VALUE
    WHEN OPERATOR = '>' THEN V1.VALUE > V2.VALUE
    WHEN OPERATOR = '<' THEN V1.VALUE < V2.VALUE
END AS VALUE
FROM EXPRESSIONS
JOIN VARIABLES V1
ON V1.NAME = LEFT_OPERAND
JOIN VARIABLES V2
ON V2.NAME = RIGHT_OPERAND