-- Write your query below
SELECT LEFT_OPERAND, OPERATOR, RIGHT_OPERAND, 
CASE 
    WHEN OPERATOR = '=' THEN 
    CASE
        WHEN V1.VALUE = V2.VALUE THEN TRUE ELSE FALSE
    END
    WHEN OPERATOR = '>' THEN
    CASE 
        WHEN V1.VALUE > V2.VALUE THEN TRUE ELSE FALSE
    END
    WHEN OPERATOR = '<' THEN
    CASE
        WHEN V1.VALUE < V2.VALUE THEN TRUE ELSE FALSE
    END
END AS VALUE
FROM EXPRESSIONS
JOIN VARIABLES V1
ON V1.NAME = LEFT_OPERAND
JOIN VARIABLES V2
ON V2.NAME = RIGHT_OPERAND